environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: Dreamshaper Latent Consistency Model
python_version: py311
requirements:
  - diffusers
  - transformers==4.35.2
  - accelerate==0.23.0
  - torch==2.1.0
  - rembg[gpu]
hf_cache:
  - repo_id: SimianLuo/LCM_Dreamshaper_v7
    allow_patterns:
      - "*.json"
      - "*.safetensors"
      - "*.bin"
resources:
  accelerator: A10G
  cpu: "1"
  memory: 2Gi
  use_gpu: true
secrets: {}
system_packages: []
